// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using shapes.Data;

#nullable disable

namespace shapes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("shapes.Models.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Shapes", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("shapes.Models.Circle", b =>
                {
                    b.HasBaseType("shapes.Models.Shape");

                    b.Property<double>("CenterX")
                        .HasColumnType("double precision");

                    b.Property<double>("CenterY")
                        .HasColumnType("double precision");

                    b.Property<double>("Diameter")
                        .HasColumnType("double precision");

                    b.ToTable("Circles", (string)null);
                });

            modelBuilder.Entity("shapes.Models.Rectangle", b =>
                {
                    b.HasBaseType("shapes.Models.Shape");

                    b.Property<double>("BottomRightX")
                        .HasColumnType("double precision");

                    b.Property<double>("BottomRightY")
                        .HasColumnType("double precision");

                    b.Property<double>("TopLeftX")
                        .HasColumnType("double precision");

                    b.Property<double>("TopLeftY")
                        .HasColumnType("double precision");

                    b.ToTable("Rectangles", (string)null);
                });

            modelBuilder.Entity("shapes.Models.Triangle", b =>
                {
                    b.HasBaseType("shapes.Models.Shape");

                    b.Property<double>("X1")
                        .HasColumnType("double precision");

                    b.Property<double>("X2")
                        .HasColumnType("double precision");

                    b.Property<double>("X3")
                        .HasColumnType("double precision");

                    b.Property<double>("Y1")
                        .HasColumnType("double precision");

                    b.Property<double>("Y2")
                        .HasColumnType("double precision");

                    b.Property<double>("Y3")
                        .HasColumnType("double precision");

                    b.ToTable("Triangles", (string)null);
                });

            modelBuilder.Entity("shapes.Models.Circle", b =>
                {
                    b.HasOne("shapes.Models.Shape", null)
                        .WithOne()
                        .HasForeignKey("shapes.Models.Circle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("shapes.Models.Rectangle", b =>
                {
                    b.HasOne("shapes.Models.Shape", null)
                        .WithOne()
                        .HasForeignKey("shapes.Models.Rectangle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("shapes.Models.Triangle", b =>
                {
                    b.HasOne("shapes.Models.Shape", null)
                        .WithOne()
                        .HasForeignKey("shapes.Models.Triangle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
